### ISSUE TITLE
ipynb link munger is broken when it's already a link to nbviewer!

### ISSUE THREAD

**Issue by davclark** [dlab-berkeley/python-berkeley#12]
An example of this exists on the front page currently.

**Comment by marwahaha** [comment]
where?

**Comment by davclark** [comment]
This is now mostly irrelevant. You should just link to ipynbs on github and not worry about it. But there's an example of something that _would have been_ changed as the last item under "Other Online Resources" [here](http://python.berkeley.edu/resources/). This is a [link to the offending line](https://github.com/dlab-berkeley/python-berkeley/commit/d76374062c2c9a7310ad5c19140910b41239a4e9#diff-f43458c8d83fa34af3b1556bb3a763e2R61).

Interestingly, while I was able to find a link to nbviewer, it seems that the javascript is no longer active that did the URL munging. And, that link is broken anyway (but has nothing to do with the original topic of this issue).

In any case, nbviewer isn't really useful anymore if the file is on github already.

**Comment by marwahaha** [comment]
Got it.
