### ISSUE TITLE
Look into page.path as enabling targeted editing

### ISSUE THREAD

**Issue by davclark** [dlab-berkeley/python-berkeley#16]
I.e., provide a direct link to the relevant "edit" page on GitHub

**Comment by davclark** [comment]
@marwahaha seems to have a solution to this in the works?

**Comment by marwahaha** [comment]
Right now, I have a "View Source" link at the bottom of each page. I can change it to "Edit this page", if you like. It takes you to the Github page, but not specifically "edit" (what if they don't have permissions?).

What do you think?

**Comment by davclark** [comment]
If you don't have commit permissions, the GitHub interface will allow you open a pull request with the edit button. So, I'd vote for "edit" as opposed to "view" source.
