### ISSUE TITLE
Have fallback for (or don't use) CDN

### ISSUE THREAD

**Issue by davclark** [dlab-berkeley/python-berkeley#17]
offline editing currently sucks until we have a reasonable CDN
fallback: Have fallback that doesn't depend on cloudflare (I guess some
javascript is loading from there?)

**Comment by marwahaha** [comment]
what does this mean?

**Comment by davclark** [comment]
It seems you have opted to use entirely locally hosted resources. So, this isn't an issue. I assume you know css and js is now being largely loaded in _includes/head.html. These could point to Content Delivery Network (CDN) links that would enable browsers to take advantage of cached versions, thus speeding up the web. You chose the "or don't use" option implicitly. Also:

http://lmgtfy.com/?q=cdn+fallback

**Comment by marwahaha** [comment]
ok, thanks for the clarification. 

So -- not a problem anymore?
