### ISSUE TITLE
Get instructors for Jan 2015 training in D-Lab!

### ISSUE THREAD

**Issue by davclark** [dlab-berkeley/python-berkeley#37]
If I can get other people to lead, it can run **Jan 12-16**.

If I need to lead, I'll just be getting back on Dec 15, so we'll have to do it that weekend (Jan 17-18).
- [X] email py4science
- [X] Post on python.berkeley.edu (but just on final event)
- [X] Tweeted as @davclark and @PyWorkParty
- [ ] Still need to be sure to hit up Titus & Greg's Software Carpentry training

**Comment by davclark** [comment]
@rochelleterman may be able to lead some stuff...

**Comment by rochelleterman** [comment]
I can do any of those, but I would greatly prefer doing it with other people!

**Comment by takluyver** [comment]
I may be able to help. Can you post some more detail of what the training involves?

**Comment by davclark** [comment]
The instructors will be somewhat free to choose. The general plan in the past has been 5 days, split into two separate logical workshops:

Programming fundamentals - introduce how to use whatever environment (in my case, BCE), command line, installing python packages, editing files, etc.

Python - 4 days of hands on. Focus on how to import functions from libraries and use them. I really like @omoju's https://github.com/omoju/hiphopathy.

Previous session was here: http://python.berkeley.edu/trainings/2014-08-berkeley-dlab.html

**Comment by omoju** [comment]
I will soon be adding more stuff to hiphopathy. I would love to teach again!

**Comment by davclark** [comment]
W004!

**Comment by arokem** [comment]
I can teach that weekend (17th-18th)

**Comment by omoju** [comment]
I can teach either on the 13th or the 16th of January

**Comment by emhart** [comment]
I'd be interested in teaching a small section.  I could probably do a morning or afternoon midweek.  Maybe that's not enough to contribute, but if it is I'd be happy to take a few hours off work to come up.  I have a hard time doing as much teaching as I did as post-doc so it's nice to get a chance locally.

**Comment by davclark** [comment]
The way we've done it in the D-Lab is 3-4 hours, either before or after lunch. That way, we avoid burn out... we just stretch it over the week. So if we run during the week, @emhart, it sounds like it'd work well to have you cover one day!

**Comment by rdhyee** [comment]
I'd be able to help out on Thursday Jan 15.   If you end up running the workshop on the weekend, I can help out on Saturday, Jan 17.

**Comment by davclark** [comment]
I just uploaded a page to organize the training. You can view it live [here](http://python.berkeley.edu/trainings/2015-01-berkeley-dlab.html). But more importantly, you can make pull requests and talk about how the training should be developed by editing `trainings/2015-01-berkeley-dlab.md`.

Note in particular that the topics are somewhat subject to change, as long as the progression makes sense. In particular, I was thinking @sbenthall might reprise his communication network analysis stuff, and @rochelleterman might discuss more "serious" text analysis in python following @omoju's simple intro to web scraping and hip hop lyrics.

@rdhyee and @omoju, I put you both down for specific days. Others are welcome to request specific days.

I'll also add that if you aren't UC staff (this includes post-docs), we can reimburse you to the tune of $25 / hour for being a lead instructor. Just let me know, and we'll start processing the paperwork for that.

**Comment by davclark** [comment]
Adding @aculich to the discussing in anticipation of his help getting the build sorted for BCE 0.2

**Comment by sbenthall** [comment]
I'm happy to do something for this but the scheduling is complicated for me. I'll be flying back on Jan 13th, the Simons Institute's Information Theory Bootcamp is during that time[1], and I'll be out of town that weekend.

As for content, I've got material for both communication network analysis and an overview of "joining the Python community", which includes some stuff on open source etiquette. Depending on who you are targeting, the latter may be more appropriate.

[1] http://simons.berkeley.edu/workshops/inftheory2015-boot-camp

**Comment by davclark** [comment]
I've updated the week and proposed a (lead) instructor for each day, along with an assistant instructor on some days. @rochelleterman is already on payroll. Other grad students or non-campus folks can talk to me about getting signed up (my github handle at berkeley.edu).

Briefly:
M: @rochelleterman 
Tu: @omoju 
W: @emhart 
Th: @takluyver 
F: @davclark

I've got @rochelleterman also assisting on Wed, and @rdhyee on Thu.

I'm also cc'ing @juanshishido as a potential D-Lab facilitator.

Still updating the page: `trainings/2015-01-berkeley-dlab.md` ([on the web](http://python.berkeley.edu/trainings/2015-01-berkeley-dlab.html)).

**Comment by rochelleterman** [comment]
Thanks Dav - looks good to me. Quick question about the programming fundamentals: Do you want me to get people up and running with BCE? Maybe we can touch base real quick in person to discuss this and other learning objectives?

**Comment by emhart** [comment]
Hey Dav, I can't instruct all day on Wednesday though, is that ok?  Should I coordinate with @rochelleterman on who's teaching when?

**Comment by davclark** [comment]
I want one lead instructor per day. Are there other days that work for you? (replied initially via email - to be clear, responding to @emhart).

Also, in case folks aren't looking at the actual schedule, the times are 1-4pm each day, but ideally someone (could be an assistant) could stay after for a bit.

**Comment by emhart** [comment]
@davclark Ahhh, I think I just had a full day stuck in my mind :).  Wednesday 1 - 4 works great for me.

**Comment by rdhyee** [comment]
Just to confirm: I'm planning to planning to show up at the D-Lab on next Thursday 1-4pm to help @takluyver.

**Comment by davclark** [comment]
FYI - responded to @rdhyee via email. Thanks everyone!
