### ISSUE TITLE
Get Instructors for May 2015 D-Lab Workshop

### ISSUE THREAD

**Issue by davclark** [dlab-berkeley/python-berkeley#39]
@davclark is available to lead Monday-Wednesday and Friday, but is willing to let other instructors take the lead. @deniederhut will lead Thursday.

The course website is [here](http://python.berkeley.edu/trainings/2015-05-berkeley-dlab.html).

**Comment by davclark** [comment]
@rdhyee, @nborwankar and @choldgraf have said they can probably help.

**Comment by rdhyee** [comment]
Yes I will help as an assistant if I don't get sucked into a week-long jury.

**Comment by deniederhut** [comment]
Do we have teaching materials for previous versions of this course?

Also, I know 0 things about containers. @davclark can you recommend a tutorial?

**Comment by davclark** [comment]
Right now, there are links on the page (linked in the initial post above). We should re-configure and update these to be coherent for evolving materials... Also, @rochelleterman has put together some good materials [here](https://github.com/rochelleterman/programming-fundamentals).

I think we should teach some basic data storage approaches. I'm thinking maybe mongo? What do y'all think?

**Comment by rochelleterman** [comment]
Sorry I'll be out of town :(
