### ISSUE TITLE
Are we updating/monitoring our tweetmail?

### ISSUE THREAD

**Issue by deniederhut** [dlab-berkeley/python-berkeley#48]
We are listing:
- https://twitter.com/PyWorkParty
- py4science@lists.berkeley.edu

Are these currently active? And/or being monitored by someone?

**Comment by marwahaha** [comment]
I'm on py4science. It has very little traffic, and is kinda used only for announcements right now (this could change, but it might be best to stay this way.)

I'm going to create a new email list for the learn python working group.

I'm not sure about twitter... I don't really want it.

**Comment by davclark** [comment]
Py4Science is a long-running mailing list. It should be considered extra-D-Lab.

The PyWorkParty account is now me. Don't worry about that either.
