### ISSUE TITLE
revamp of python-berkeley site

### ISSUE THREAD

**Issue by marwahaha** [dlab-berkeley/python-berkeley#50]
I'd like to merge this site with the Learn Python working group site. This is the next iteration of "PyWorkersParty" and I think it makes sense to keep them together.

I can do the grunt work, but I was planning to keep the theme from the Learn Python website.
http://marwahaha.github.io/learnpython/

I can update the resources accordingly.
Thoughts?

**Comment by deniederhut** [comment]
By theme, do you mean CSS? Because your stylesheets don't render on my machine.

**Comment by marwahaha** [comment]
I mean something like this:

I would like [this page](http://marwahaha.github.io/learnpython) to replace the current python.berkeley.edu, and all information to be ported over. I've already done most of the legwork -- see, for example, [community](http://marwahaha.github.io/learnpython/community) and old [events](http://marwahaha.github.io/learnpython/events/archive) and [trainings](http://marwahaha.github.io/learnpython/trainings).

The only thing left to do is to merge the learning resources page: I've got a copy [here](http://marwahaha.github.io/learnpython/learn) and the old python.b.e information [here](http://marwahaha.github.io/learnpython/old_resources). I could use some help here...

After we merge the two, the learnpython site has all the information of the old python.b.e site, plus some. So, I think we should use that for the python.b.e site.

Thoughts?

**Comment by davclark** [comment]
@marwahaha and I talked about this IRL. It seems the merge is good. Can we close this?
